### ISSUE TITLE
[B]Crash with Quark When Placing Vanilla Dusts

### ISSUE THREAD

**Issue by micahlaster** [ImSpacee/Silky-Spawners#7]
game crashes when placing vanilla dusts due to a null pointer on the entity this is because the entity can be null and you have asserted that it is not null in your block place event which throws an error as it is null in order to fix this you could add a try catch to that method or find another way to make sure entity is not null before trying to use it

**Comment by ImSpacee** [comment]
I'll be recoding SilkySpawners soon, for 1.12.2 and for newer versions.
Right now, i'm rather busy with personal life and server-related issues.

This might take a while, so for now I suggest you use another "Silky-Spawner" mod.

**Comment by Codetoil** [comment]
The commit probably fixed the issue. Can’t check as I’m on my iPad atm. I’ll be sure to test the next time I’m on the computer.
